public class checkRecurisveRun {
    
    public static boolean firstRun = true;
    public static boolean closeCCECAndCases = true;
    public static boolean prospectPickupToPuckup = true;
    public static boolean blukExceptionHandle = true;
    public static boolean ccecCreation = true;
	public static boolean complaintClosureUpdate = true;
    public static boolean derivingLocationPickupOU = true;
    public static boolean shareCase = true;
    public static boolean pickupRequestApi = true;
     public static boolean rurnCustomer360Batch = true;
}