public class CheckRecursive {
    /*
* Author : Ashish(akumar4@kloudrac.com)
* Description : This class for check recursion
* Test Class Name : AmountRollupTest(100%)
* Created Date : 09-05-2022
* Modified Date : 09-05-2022
*/
    
    public static boolean runBeforeInsert = true;
    public static boolean runAfterInsert = true;
    public static boolean runBeforeUpdate = true;
    public static boolean runAfterUpdate = true;
    public static boolean runBeforeDelete = true;
    public static boolean runAfterDelete = true;
    public static boolean runInsertUpdaateunDelete = true;
     public static boolean smsApiCall = true;
     public static boolean exceptionCloseRun = true;
    
}