public class GatiMDMCreationResponseItemWrapper {
	@AuraEnabled public String Oppurtunity {get; set;}
    @AuraEnabled public String Existing_Customer_Code {get; set;}
    @AuraEnabled public String Existing_Customer_Contract {get; set;}
    @AuraEnabled public String Customer_Pan_Number {get; set;}
    @AuraEnabled public String Customer_Phone_Number {get; set;}
    @AuraEnabled public String Customer_Email_ID {get; set;}
    @AuraEnabled public String Customer_Name {get; set;}
    @AuraEnabled public String Customer_Category {get; set;}
    @AuraEnabled public String Customer_OU_Code {get; set;}
}