@isTest
public class SanityCheckEmailOnAccount_SchedulerTest {
/*   @istest static void sanityTest(){
        
        
        SanityCheckEmailOnAccount_Scheduler job = new SanityCheckEmailOnAccount_Scheduler();
        String cronEXPR = '0 0 0 1 1/3 ? *';        
         String jobid = System.schedule('Sanity check email', cronEXPR, job);
         SanityCheckEmailOnAccount_Scheduler.scheduleIt();
        
            //CronTrigger ct = [Select id , CronExpression from CronTrigger where id = :jobId];
           // System.assertEquals(CRON_EXPR ,ct.CronExpression);
	} */
}