@isTest
public class TestLeadAssignmentAsync {
    /*
    public static testMethod void callAsyncMethod()
    {
        Test.startTest();
       List<List<string>> ld=new  List<List<string>>();
     List<String> lst =new List<String>();
        
        
         list <Lead> leads=TestFactory.getLead2(1,'ld1','ld2');
        lst.add(Leads[0].id);
        
        User u=TestFactory.getUser1('Tripathy','atrip','America/Los_Angeles','en_US','UTF-8','en_US','test.bdfshead1@gati.com','standarduser1@testorg.com');
      
           lst.add(u.id);
        ld.add(lst);
       
        LeadAssignmentAsync.callAsyncMethod(ld);
       // update leads;
        
        
         Test.stopTest();
       
        
    }*/
    
   
}